export const workFlows = {
  "home-page-workflow":[

    {
      elementSelector: "#home",
      header:"home tab",
      content: "This is the name of the author on the Home page",
      elementType: "normal",
      hasBackButton: false,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextElement: "#edit",
    },
    {
      elementSelector: "#edit",
      header:"edit tab",
      content: "This is the slogan section on the Home page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextElement: "#save",
    },
    {
      elementSelector: "#save",
      header:"save tab",
      content: "This is the welcome section on the Home page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextElement: "#save-as",
    },
    {
      elementSelector: "#save-as",
      header:"save as tab",
      content: "This is the link to join section on the about page",
      elementType: "link",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextPage: "/about",
      nextElement: "#highlights",
    },
    {
      elementSelector: "#delete",
      header:"delete tab",
      content: "This is the highlight section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      previousPage: null,
      previousElement: "#save-as",
      nextElement: "#open",
    },
    {
      elementSelector: "#open",
      header:"open tab",
      content: "This is the certificates section on the Home page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      previousElement: "#delete",
      nextElement: "#file",
    },
    {
      elementSelector: "#file",
      header:"file tab",
      content: "This is the why section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextPage: null,
    },
    {
      elementSelector: "#zoom",
      header:"zoom tab",
      content: "This is the home tab on the Home page",
      elementType: "link",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      nextPage: "/home",
      previousPage: "/about",
      previousElement: "#file",
    },
    {
      elementSelector: "#hide",
      header:"hide tab",
      content: "This is the company profile section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
      previousPage: "/home",
      previousElement: "#zoom",
      nextElement: "#certificates",
    },
    {
      elementSelector: "#download",
      header:"download tab",
      content: "This is the process section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
      previousPage:null,
      previousElement: "#zoom",
      nextPage: null,
    },
    {
      elementSelector: "#image",
      header:"image tab",
      content: "This is the process page section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
    },
    {
      elementSelector: "#heading",
      header:"heading tab",
      content: "This is the processed section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
    },
    {
      elementSelector: "#description",
      header:"description tab",
      content: "This is the products section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
      previousPage: null,
      previousElement: "#heading",
      nextPage: null,
    },
    {
      elementSelector: "#heading1",
      header:"heading1 tab",
      content: "This is the  product details section on the About page",
      elementType: "normal",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
    },
    {
      elementSelector: "#descreption1",
      header:"descreption1 tab",
      content: "This is the  contact section on the About page",
      elementType: "link",
      hasBackButton: true,
      hasNextButton: true,
      backButtonLabel: "Back",
      nextButtonLabel: "Next",
      buttonAction: "moveToNextStep",
      previousPage: "/products",
      previousElement: "#product-id",
      nextPage: "/contact",
    }, 
  ]
}